#!/bin/bash

if [ $# -ne 0 ];then
 /bin/echo 'Error: No arguments are supported.'
 exit 1;
fi

if [ "$RR_WITH_ENV" = "1" ]; then
. `rr_root`/tools/vmgr/runner/bin/rr_runme.sh  --chain_dir /home/lacp3102/APP1/UdeS_S8_APP1/formatif/gei816-formatif-amorce/verif/regression_area/example_session.lacp3102.24_09_22_16_53_45_0377/chain_1 --group_dir /home/lacp3102/APP1/UdeS_S8_APP1/formatif/gei816-formatif-amorce/verif/regression_area/example_session.lacp3102.24_09_22_16_53_45_0377/chain_1/example_group --run_id 4 --seed random --e_seed random --sv_seed random 
else
`rr_root`/tools/vmgr/runner/bin/rr_runme.sh  --chain_dir /home/lacp3102/APP1/UdeS_S8_APP1/formatif/gei816-formatif-amorce/verif/regression_area/example_session.lacp3102.24_09_22_16_53_45_0377/chain_1 --group_dir /home/lacp3102/APP1/UdeS_S8_APP1/formatif/gei816-formatif-amorce/verif/regression_area/example_session.lacp3102.24_09_22_16_53_45_0377/chain_1/example_group --run_id 4 --seed random --e_seed random --sv_seed random 
fi
